@extends('layouts.app')
@section('css')
<style>
	.navbar-static-top {
		display: none;
	}
	.navbar-static-side {
		display: none;
	}
	#page-wrapper {
		padding: 0;
		margin: 0;
	}
</style>
@endsection 

@section('content')
<div class="login-container" style:"margin-bottom: 0px;">
	<div id="wrapper">
	<div id="page-wrapper" class="gray-bg tree-bg" style="margin: 0px; background-repeat: space; background-size: unset;">
		<div class="wrapper wrapper-content animated fadeInRight">
			<div class="row">
				<div class="col-md-8 col-md-offset-2 m-t-lg clearfix">
					<div class="ibox-title">
						<h3 style="float:left;">Terms & Conditions</h3>
						<a href="{{ URL::to('/register') }}" class="btn btn-primary btn-xs pull-right">
						<span class="fa fa-arrow-circle-left"></span>&nbsp;Back to Registration</a>
					</div>
					<div class="ibox-content clearfix">
<h4>Binding Agreement</h4>
<p>Welcome to&nbsp;<a href="http://www.trafficroots.com/">Traffic Roots</a>, a service brought to you by Traffic Roots, Inc ("Traffic Roots"). Traffic Roots is providing its services to you subject to the following Terms of Use (the "Terms"), as may be updated by Traffic Roots from time to time in Traffic Roots sole discretion without further notice to you, except where otherwise indicated. The latest version of the Terms is always available for your review on this page. Additionally, certain of our services are subject to additional rules and regulations that are unique to such services. Where additional rules or regulations are applicable, you will be notified and be required to agree to such additional rules and regulations prior to your use of such services. Also, in some circumstances Traffic Roots may offer services that are subject to terms of use that are different from the Terms. In such cases, you will be prompted to accept such terms of use prior to your use of such services. References to "you" in these Terms means you, your duly authorized representatives and the entity you represent.</p>
						
<h4>Traffic Roots Services</h4>
<p>Traffic Roots provides online marketers, agencies, publishers and networks with a Catalog of Media available for purchase, and provides Media property owners a safe and efficient marketplace for the sale of online advertising inventory, and the monitoring of the overall efficacy of such efforts, all with an eye toward bringing transparency and efficiency to the participants of the online marketing industry (collectively, the "Services"). You understand and agree that as part of your use of the Services, you may in certain circumstances receive communications from Traffic Roots, including without limitation in response to a research inquiry, to verify the accuracy of listings, to validate the legitimacy of bids, to confirm a purchase or sale or with respect to order fulfillment, and that these communications form an essential part of your use of the Services from which you cannot opt out. In all cases, you acknowledge and agree that the Services are provided to you "AS-IS" and that Traffic Roots assumes no responsibility for the accuracy or timeliness of any information provided to you through the Services or with respect to the fulfillment of orders placed through the Services.</p>
 
<h4>Registration with Traffic Roots</h4>
<p>For most Services, you will be required to register with Traffic Roots prior to being able to utilize such Services, including providing all registration information. As consideration for the use of such Services, you represent and warrant that:</p>
<p>all Registration Information provided by you is true, accurate, current and complete at the time of registration and you undertake to update all such Registration Information if at any time during your use of the Services it becomes untrue or inaccurate;</p>
<p>you are at least eighteen (18) years of age;</p>
<p>you, or the entity you represent, has not, within the last twenty-four (24) months, declared bankruptcy, made or been forced to make an assignment for the benefit of creditors, been adjudicated bankrupt and/or voluntarily commenced a liquidation;</p>
<p>you are legally authorized to conduct your business, including conducting such activities as are contemplated by use of the Services in whatever manner so used;</p>
<p>you will use the Services for the sole and exclusive purpose of conducting market research, buying and/or selling internet advertising, and tracking fulfillment of orders purchased or sold through the Services on your own behalf, or on behalf of your clients.</p>
<p>If any of your representations and warranties with respect to (a) through (e) above is untrue, inaccurate, not current or incomplete, you are not authorized to use the Services and Traffic Roots may, in its sole discretion, prevent your use of the Services or invalidate any action taken with respect to your use of the Services, provided that Traffic Roots may also, notwithstanding a violation of such representations and warranties, hold you completely and totally liable for any actions taken with respect to your use of the Services, including for payment of any fees you may incur using such Services, if any.</p>
<p>Traffic Roots reserves the right to refuse access to the Services to anyone at any time and for any reason in its sole discretion.</p>
<p>You understand and agree that in the course of registration, you will be asked to provide a secure password and log in information for purposes of accessing those Services that require registration. You certify that you will only provide such secure password and log in information to those individuals associated with you that are duly authorized to act on your behalf with respect to the Services. You acknowledge and agree that you will be solely responsible for any and all activity of whatever nature conducted through the Services using such secure password and log in information. Traffic Roots will not be responsible for any loss, damage and/or unauthorized use of your secure password, log in information or related accounts. You agree to notify Traffic Roots immediately of any unauthorized use or your secure password, log in information or related accounts as soon as you become aware of any such unauthorized usage. In order to assist Traffic Roots in maintaining the security of all secure passwords, log in information and all related accounts and as further consideration for your use of the Services, you agree to properly log off of secure areas within&nbsp;<a href="http://www.trafficroots.com/">Traffic Roots</a>&nbsp;at the end of each such usage.</p>
<p>If, at any time, you provide any Registration Information, by update or otherwise, that is untrue, inaccurate, not current or incomplete, or if Traffic Roots has reasonable grounds to suspect that such Registration Information is untrue, inaccurate, not current or incomplete, Traffic Roots has the right to terminate or suspend your access to all or a portion of the Services. Notwithstanding any such suspension or termination, you will remain liable and solely responsible for any and all activity of whatever nature conducted through the Services.</p>
 
<h4>Traffic Roots Privacy Policy</h4>
<p>Certain information you provide to Traffic Roots, including without limitation the Registration Information, is subject to the terms of our Privacy Policy, as may be updated from time to time in Traffic Roots sole discretion, the latest version of which is available&nbsp;<a href="https://trafficroots.com/">here</a>. You understand and agree that your use of all or any portion of the Services constitutes acceptance of Traffic Roots collection and use (as provided for in the Privacy Policy) of all information, including the Registration Information, that you provide to Traffic Roots, including the transfer of all such information to the United States and/or other countries for storage, processing and use by Traffic Roots and its affiliates.</p>
<h4>Traffic Roots Intellectual Property Policy</h4>
<p>Traffic Roots respects the intellectual property of others and by use of the Services, you agree to do the same, including without limitation, the patents, copyrights and trademarks of others. Traffic Roots reserves the right to suspend or terminate access to the Services of any party that it believes, in its sole discretion, is violating the patent, copyright or trademark of others.</p>
<p>For the purposes of the acceptance of these terms and conditions, which will be considered an agreement, ("Agreement"), &ldquo;Confidential Information&rdquo; shall mean any and all technical and non-technical information, whether in written, verbal or any other form, belonging to or disclosed by each disclosing party and designated as confidential, including copyrights, trade secrets, and other proprietary information, including, but not limited to, techniques, sketches, drawings, models, inventions, know-how, processes, apparatus, equipment, algorithms, software programs, software source documents and formulae related to the current, future and proposed products, documents and services of such disclosing party, and further includes, without limitation, any information of such disclosing party concerning research, experimental work, development, design details and specifications, engineering, financial information, procurement requirements, purchasing,&nbsp;customer lists, business forecasts, sales and merchandising, and marketing plans and information. The disclosing party can be either party, Traffic Roots or the User. The receiving party can be either party or an employee of Traffic Roots, receiving information from either Traffic Roots itself or User.&nbsp;</p>
<p>Each receiving party agrees that it will not copy or use in any way Confidential Information.</p>
<p>Each receiving party agrees that it shall disclose the disclosing party's Confidential Information only to those of its employees who need to know such information and provided that the receiving party has ensured that such employees will be bound by terms and conditions substantially similar to those of this Agreement. Each receiving party also agrees to advise each such employee, before he or she receives access to the Confidential Information, of the obligations of the receiving party under this Agreement.</p>
<p>Each receiving party agrees that it shall take all reasonable steps to safeguard the disclosing party's Confidential Information including at a minimum, those steps that it takes to protect its own Confidential Information, and that it shall be responsible to the disclosing party for any disclosure or misuse of Confidential Information which results from a failure to comply with this Agreement.</p>
<p>Each receiving party further agrees that it shall not publish, or otherwise disseminate or disclose any of the disclosing party's Confidential Information to any third party.</p>
<p>For the purposes of this Agreement, Confidential Information shall not include any information which:</p>
<ul>
	<li>(a) is required to be disclosed by law, provided however, that if the receiving party receives a subpoena or similar document requiring it to disclose the disclosing party&rsquo;s Confidential Information, the receiving party shall notify promptly the disclosing party so that the disclosing party can take appropriate action to suppress the disclosure of its Confidential Information or else insure that its Confidential Information is disclosed under confidentiality provisions only.</li>
	<li>(b) Any information previously available to the public at the date of disclosure.</li>
	<li>(c) Is documented and notarized as independently developed by the receiving party without reference to the disclosed Confidential Information.</li>
</ul>
<p>All Confidential Information reduced to writing and furnished to the receiving party by the disclosing party shall remain the property of the disclosing party and shall be returned to it immediately upon termination of this Agreement or upon the disclosing party's request for any reason, together with any and all copies thereof.</p>
<p>The parties' obligations with respect to each other's Confidential Information under Sections [1] through [7] above shall remain in effect for a period of five (5) years from the date of the last disclosure of Confidential Information made hereunder.</p>
<p>Since unauthorized disclosure of Confidential Information will diminish the value of the proprietary interests that are the subject of this Agreement, if the receiving party breaches any of its obligations hereunder, the disclosing party may be entitled to equitable relief to protect its interest therein, including but not limited to injunctive relief, as well as money damages.</p>
<p>Non-Circumvention and Non-compete. Users, employees of all parties and Traffic Roots agrees that he will not use any of disclosing party&rsquo;s proprietary designs, trademarks, names, research, development and clinical results, nor it will use similar designs, trade marks and names, for manufacturing and/or selling similar products to any entity worldwide for a period of ten (10) years from the execution of this Agreement.</p>
<p>This Agreement shall be effective as of the later date of execution signed below and will continue in effect for five (5) years from such date, in accordance with the confidentiality provisions of any detailed agreement which the parties may enter into.</p>
<p>Attorneys' Fees<em>. </em>In the event of any litigation concerning any controversy, claim or dispute between the parties hereto, arising out of or relating to this Agreement or the breach hereof, or the interpretation hereof, the prevailing party shall be entitled to recover from the losing party reasonable expenses, attorneys' fees, and costs incurred therein or in the enforcement or collection of any judgment or award rendered therein. The proper venue for such action will be San Diego, California.</p>
 
<h4>Copyright Matters</h4>
<p>With respect to copyright matters, re-use of any of Traffic Roots editorial content and graphics for any purpose without Traffic Roots permission is strictly prohibited. All graphics and editorial content on&nbsp;<a href="http://www.trafficroots.com/">Traffic Roots</a>&nbsp;and any related sites are protected by U.S. copyright, international treaties, and other applicable copyright laws and may not be copied without the express permission of Traffic Roots, which reserves all rights. Permission to use Traffic Roots' content is granted on a case-by-case basis. Do not copy or adapt the HTML or other code that TRAFFIQ creates to generate pages. It also is covered by Traffic Roots copyright.</p>
<p>As a regular part of our business, Traffic Roots displays advertisements and product listings from a wide variety of companies. Traffic Roots is not in a position to arbitrate disputes between the owners of intellectual property rights and companies who advertise or list their products on Traffic Roots sites. However, as a courtesy to owners of intellectual property rights, Traffic Roots is willing to perform a limited investigation of reasonable complaints. However, Traffic Roots provides no guarantee that we will remove the allegedly infringing materials from Traffic Roots sites.&nbsp;</p>
<p>Traffic Roots encourages the owners of intellectual property rights who believe their rights are being infringed by a company who advertises or lists its products on our site to resolve their disputes directly with that company.</p>
<p>If your materials have been removed from our Services, including without limitation removal from&nbsp;<a href="http://www.trafficroots.com/">Traffic Roots</a>, based on the complaints of another party, Traffic Roots will provide you with notice of the removal of such materials due to alleged infringement of a third party's intellectual rights. Traffic Roots will also provide you with the e-mail address of the complaining party so that you may attempt to resolve the issue. Traffic Roots may restore your materials upon notification from the complaining party that the dispute has been resolved.</p>
 
<h4>Trademark Matters</h4>
<p>Traffic Roots, the Traffic Roots logo, are trademarks of Traffic Roots, Inc. (collectively, the \\\"Traffic Roots\\\"). You agree not to display or use in any manner the Traffic Roots Marks without Traffic Roots prior written consent.</p>
<h4>International Usage</h4>
<p>You acknowledge and agree that, in light of the global reach of the Internet, you will at all times comply with all local rules, laws and treaties, of whatever sort or nature, including without limitation, regarding transacting business online, the usage of all data, information, transactional data, text, software, music, sound, photographs, graphics, video, messages, tags, or other materials (collectively, the \\\"Content\\\"), the transmission of technical data exported from the United States or your country of residence or organization, in connection with your use of the Services.</p>
 
<h4>Use and Storage Relating to the Services</h4>
<p>You acknowledge and agree that from time to time Traffic Roots may establish general practices and limits with respect to the use of its Services, such as, without limitation, the number of days a Listing may be posted, the number of days for which summary account information will be maintained, the number of days a Listing may cover, the number of days historical transaction data will be maintained and/or accessible, and the number of Listings an account may create, the number of campaigns you may create, the number of advertisement files you may upload to Traffic Roots, the number of bids you may submit, the maximum number of reports, research requests or other information queries that may be requested in a given time period, and the maximum amount of time you may be logged into your account in a given time period, among others. By using the any portion of the Services, you acknowledge and agree that you will be subject to any and all such general practices and limitations and further, that Traffic Roots reserves the right, in its sole discretion, to alter these general practices and limitations from time to time, as it deems necessary or appropriate. You also acknowledge and agree that, by using any portion of the Services, you have no continuing rights to the information stored by Traffic Roots.&nbsp;</p>
 
<h4>Termination, Suspension or Modification of Services</h4>
<p>You acknowledge and agree that Traffic Roots has the right at any time and in such frequency as it determines to suspend, discontinue, or terminate the Services, in whole or in part, with or without notice to you. You further acknowledge and agree that Traffic Roots shall not be liable to you or any third party for any such suspension, discontinuance, or termination of the Services for any reason.</p>
<p>Under some circumstances, Traffic Roots reserves the right to terminate your access to the Services, in whole or in part, immediately and without notice to you. Reasons for such a termination include, without limitation, (i) a breach or breaches of the Terms or other agreements and/or guidelines incorporated herein by reference, (ii) engagement by you in conduct that is deemed by Traffic Roots, in it sole and exclusive judgment, to be fraudulent or constituting an illegal act, (iii) a request made by law enforcement or other government agencies, (iv) a request made by you (self-selected termination); (v) suspension, discontinuance, or material modification of the Services or a portion thereof; (vi) unanticipated technical or security problems or issues; (vii) periods of extensive account inactivity; (viii) failure by you to pay or timely pay any fees, charges, or other monies due Traffic Roots or such third parties as it may serve as agent for in connection with settling a transaction; and (ix) violation of any agreement entered into in connection with your use of the Services. Any termination by Traffic Roots of your account and/or access to the Services will include, without limitation (i) removal of access to any and all offerings comprising the Services, (ii) deletion of your secure password, log in information and related accounts, including all historical transaction data and summaries, if any, and (iii) a prohibition against your ability to use the Services at any time in the future. You acknowledge and agree that any termination for cause is in Traffic Roots\\\' sole and exclusive discretion and that any termination of your access to the Services and/or your account shall not cause Traffic Roots to be liable to you or any third party for any reason.</p>
<p>Notwithstanding anything to the contrary set for herein, Publisher Payments are related to the number of valid clicks on Ads displayed on your Properties, the number of valid impressions of Ads displayed on your Properties, or other valid events performed in connection with the display of Ads on your Properties, in each case as determined by Traffic Roots and Traffic Roots alone.</p>
<p>Except in the event of termination, Traffic Roots will pay Publishers by the end of the calendar month following any calendar month in which the earned balance in your Account equals or exceeds the applicable payment threshold. Unless expressly authorized in writing by Traffic Roots, you may not enter into any type of arrangement with a third party where that third party receives payments made to you under the Agreement or other financial benefit in relation to the Services.</p>
<p>Payments will be calculated solely based on Traffic Roots accounting and Traffic Roots impression counts. By accepting these terms, you expressly agree to these methods herein and waive any right to use any third-party data in relation to any claim against Traffic Roots. Payments to you may be withheld to reflect or adjusted to exclude any amounts refunded or credited to advertisers and any amounts arising from invalid activity, as determined by Traffic Roots in its sole discretion. Invalid activity is determined by Traffic Roots in all cases and includes, but is not limited to, (i) spam, invalid queries, invalid impressions or invalid clicks on Ads generated by any person, bot, automated program or similar device, including through any clicks or impressions originating from your IP addresses or computers under your control; (ii) clicks solicited or impressions generated by payment of money, false representation, or requests for end users to click on Ads or take other actions; (iii) Ads served to end users whose browsers have JavaScript disabled; (iv) Ads served to end users containing malware or other malicious code or elements; and (v) clicks or impressions co-mingled with a significant amount of the activity described in (i, ii,iii&nbsp;and iv) above.</p>
<p>In addition to our other rights and remedies, we may (a) withhold and offset any payments owed to you under the Agreement against any fees you owe us under the Agreement or any other agreement, or (b) require you to refund us within 30 days of any invoice, any amounts we may have overpaid to you in prior periods. If you dispute any payment made or withheld relating to the Services, you must notify Traffic Roots in writing within 30 days of any such payment. If you do not, any claim relating to the disputed payment is waived. If an advertiser whose Ads are displayed on any Property defaults on payment to Traffic Roots, we may withhold payment or charge back your account.</p>
<p>To ensure proper payment, you are responsible for providing and maintaining accurate contact and payment information in your Account. You are responsible for any charges assessed by your bank or payment provider.</p>
<p>As between you and Traffic Roots, Traffic Roots is responsible for all taxes (if any) associated with the transactions between Traffic Roots and advertisers in connection with Ads displayed on the Properties. You are responsible for all taxes (if any) associated with the Services, other than taxes based on Traffic Roots&lsquo; net income. All payments to you from Traffic Roots in relation to the Services will be treated as inclusive of tax (if applicable) and will not be adjusted.</p>
 
 
 
<h4>Proprietary Rights of Traffic Roots and Third Parties</h4>
<p>By using the Services, in whole or in part, you acknowledge and agree that the Services, any software necessarily used in connection therewith (collectively, the \\\"Software\\\") and any information or Content derived from any such usage constitutes confidential and proprietary information of Traffic Roots that is protected by applicable intellectual property and other laws. You also acknowledge and agree that Content provided or made available to you by other third parties using the Services may be protected by trademarks, service marks, copyrights, patent rights or other proprietary rights and laws. Accordingly, you acknowledge and agree that you will not, unless expressly authorized in writing by Traffic Roots or the relevant third party provider of Content, as applicable, rent, sell, loan, lease, modify, distribute, reverse engineer, or create derivative works based on the Services, the Software, or the Content, either in part or in their entirety. Traffic Roots hereby grants you a personal, non-transferable, and non-exclusive right and license to use the object code of its Software for purposes of using the Services for the purposes set for in Section 2 above, provided (i) you do not copy, modify, reverse engineer, reverse assemble, create a derivative work from, or otherwise attempt, in any way, to discover any source code, sell, assign, sublicense, or otherwise transfer in any way rights in the Software, or allow any third party to do any of the foregoing, and/or (ii) your right to use the Services for which the Software has been made available to you has not been suspended or terminated by Traffic Roots, for any reason, in whole or in part. You agree not to modify the Software in any manner or form, or use any modified versions of the Software, for any purpose, including without limitation, unauthorized access to the Services. You agree that you will not access or attempt to access the Services by any means other than through the interface provided to you by Traffic Roots for such purposes of accessing the Services.</p>
 
<h4>Proprietary Rights of Content Submitted By You; Use of Transactional Data</h4>
<p>While Traffic Roots does not make any claim as to ownership of Content you may submit in connection with your use of the Services or otherwise make available, by using the Services, you hereby grant Traffic Roots a worldwide, royalty-free and non-exclusive license to use, distribute, reproduce, modify, aggregate, adapt, publicly perform and publicly display such Content on the publicly accessible areas of the Services for purposes of promoting the Services and providing the Services to you and other third party users of the Services for so long as you continue to provide any such Content on or through the Services, subject to termination at such time as you or Traffic Roots removes such Content from inclusion in the Services. For purposes of clarity, those areas of the Services that are \\\"publicly available\\\" include all areas of the Services that are accessible by the general public, whether registered with Traffic Roots pursuant to Section 3 above or otherwise, as well as those portions of the World Wide Web that are not hosted and/or served by Traffic Roots but are accessible via hypertext and other links. Additionally, you represent and warrant that you have all requisite rights and interests to all Content you may submit in connection with your use of the Services or otherwise make available, by using the Services.&nbsp;</p>
<p>Notwithstanding anything to the contrary set forth above in this Section 11, you hereby grant to Traffic Roots a perpetual, irrevocable, worldwide, royalty-free and non-exclusive license to use, distribute, reproduce, modify, aggregate, adapt, publicly perform and publicly display that portion of the Content that constitutes transactional data with respect to the use of the Services, including without limitation, sales data, click-through data, winning bid price data, auction length data, and ratings and opinions submitted by you in connection with your use of the Services (collectively, the \\\"Transactional Data\\\").</p>
 
<h4>Hypertext links to Third Party Websites</h4>
<p>In the course of your use of the Services, you may be provided with hypertext links to other Internet web sites and/or resources over which Traffic Roots has no control, including without limitation with respect to the content of such other Internet web sites and/or resources. By using the Services, you acknowledge and agree that Traffic Roots is not responsible for any such Internet web sites and/or resources in any way, including without limitation, the content of such web sites and the availability of such web sites. Furthermore, you acknowledge and agree that Traffic Roots, by including such hypertext links in the Services, does not purport to endorse and is not in any way responsible or liable for any of the services, products, content, advertising or other materials appearing on or available through any such Internet web sites and/or resources, including without limitation any damages or losses resulting from or alleged to be resulting from or in connection with use of or reliance on any such services, products, content, advertising or other materials appearing on or available through any such Internet web sites and/or resources.</p>
 
<h4>Warranties Disclaimer</h4>
<p>IT IS EXPRESSLY UNDERSTOOD AND AGREED BY YOU THAT:</p>
<p>THE SERVICES ARE PROVIDED SOLELY ON AN \\\"AS-IS\\\" AND \\\"AS AVAILABLE\\\" BASIS. YOUR USE OF THE SERVICES IS AT YOUR SOLE AND EXCLUSIVE RISK. Traffic Roots AND ITS OFFICERS, EMPLOYEES, AGENTS, AFFILIATES, PARTNERS, LICENSORS, PARENTS AND SUBSIDIARIES EXPRESSLY DISCLAIM ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION THE IMPLIED WARRANTIES OF MERCHANTABILITY, SATISFACTORY QUALITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT OR ANY IMPLIED WARRANTY ARISING FROM COURSE OF PERFORMANCE OR COURSE OF DEALING.</p>
<p>Traffic Roots AND ITS OFFICERS, EMPLOYEES, AGENTS, AFFILIATES, PARTNERS, LICENSORS, PARENTS AND SUBSIDIARIES ARE NOT RESPONSIBLE FOR AND YOU ARE SOLELY AND EXCLUSIVELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER, ANY LOSS OF DATA AND ANY OTHER NEGATIVE CONSEQUENCES THAT MAY BE CAUSED BY YOUR USE OF THE SERVICES AND ANY MATERIALS ACCESSED, VIA DOWNLOAD OR OTHERWISE, FROM THE SERVICES.</p>
<p>ANY MATERIALS, INCLUDING WITHOUT LIMITATION INFORMATION, RECORDS, REPORTS, AND RESEARCH, ACCESSED, VIA DOWNLOAD OR OTHERWISE, THROUGH THE SERVICES ARE ACCESSED AT YOUR SOLE AND EXCLUSIVE RISK AND DISCRETION.</p>
<p>Traffic Roots AND ITS OFFICERS, EMPLOYEES, AGENTS, AFFILIATES, PARTNERS, LICENSORS, PARENTS, AND SUBSIDIARIES MAKE NO WARRANTY, EXPRESS OR IMPLIED, THAT (i) THE SERVICES, INCLUDING WITHOUT LIMITATION MATERIALS PROVIDED TO YOU THROUGH THE SERVICES (e.g., INFORMATION, RECORDS, REPORTS AND RESEARCH) WILL BE ERROR-FREE, ACCURATE, TIMELY, SECURE, RELIABLE OR UNINTERRUPTED, FREE FROM VIRUSES, BUGS, DEFECTS OR DEFICIENCIES (ii) THE SERVICES WILL MEET YOUR REQUIREMENTS, (iii) ANY LISTINGS PURCHASED AND/OR ORDER FULFILLED AND/OR OTHERWISE OBTAINED THROUGH YOUR USE OF THE SERVICES WILL BE DELIVERED TO YOU IN A TIMELY MANNER, IN WHOLE OR IN PART, OR AT ALL, WILL CONFORM TO THE SPECIFICATIONS SET FORTH IN ANY LISTING, IN WHOLE OR IN PART, OR WILL OTHERWISE MEET YOUR EXPECTATIONS, (iv) THE LISTINGS PURCHASED AND/OR THE ORDERS FULFILLED AND/OR OTHERWISE OBTAINED THROUGH YOUR USE OF THE SERVICES WILL YIELD ANY PARTICULAR RESULTS FOR YOU, AND (v) ANY ERRORS IN THE SERVICES AND/OR THE SOFTWARE WILL BE CORRECTED. NOTWITHSTANDING ANYTHING TO THE CONTRARY SET FORTH IN THIS SECTION 13(d), IN THE EVENT A SUBSEQUENT AGREEMENT ENTERED INTO IN CONNECTION WITH YOUR USE OF THE SERVICES PROVIDES FOR WARRANTIES CONTRADICTED BY THIS SECTION 13(d), THE WARRANTIES SET FORTH IN SUCH SUBSEQUENT AGREEMENT WILL CONTROL AND SUPERSEDE THIS SUBSECTION WITH RESPECT TO SUCH PARTICULAR SERVICES.</p>
<p>NO INFORMATION, ADVICE, OR INSTRUCTION, REGARDLESS OF FORM OF COMMUNICATION, PROVIDED TO YOU FROM Traffic Roots, WHETHER THROUGH USE OF THE SERVICES OR FROM Traffic Roots\\\' OFFICERS, EMPLOYEES, AGENTS, AFFILIATES, PARTNERS, LICENSORS, PARENTS AND SUBSIDIARIES, WILL CREATE ANY WARRANTY OTHER THAN THOSE EXPRESSLY SET FORTH IN THESE TERMS.</p>
 
<h4>Limitation of Liability</h4>
<p>YOU EXPRESSLY UNDERSTAND AND AGREE THAT Traffic Roots AND ITS OFFICERS, EMPLOYEES, AGENTS, AFFILIATES, PARTNERS, LICENSORS, PARENTS AND SUBSIDIARIES SHALL NOT BE LIABLE TO YOU FOR ANY DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, OR EXEMPLARY DAMAGES, INCLUDING WITHOUT LIMITATION DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES RESULTING FROM: (i) THE USE OR THE INABILITY TO USE THE SERVICES, (ii) UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR ACCOUNT, TRANSMISSIONS AND/OR DATA, (iii) THE COST OF PROCUREMENT OF SUBSTITUTE GOODS AND SERVICES RESULTING FROM ANY GOODS, DATA, INFORMATION AND/OR SERVICES PURCHASED OR OBTAINED OR MESSAGES RECEIVED OR TRANSACTIONS ENTERED INTO THROUGH OR FROM THE SERVICES, (iv) STATEMENTS OR CONDUCT OF ANY THIRD PARTY USING OR MADE AVAILABLE ON OR THROUGH THE SERVICES, AND/OR (v) ANY OTHER MATTERS RELATING TO THE SERVICES.</p>
<p>NOTWITHSTANDING ANYTHING TO THE CONTRARY SET FORTH IN THIS SECTION 14, IN THE EVENT A SUBSEQUENT AGREEMENT ENTERED INTO IN CONNECTION WITH YOUR USE OF THE SERVICES PROVIDES FOR TERMS WITH RESPECT TO LIMITATION OF LIABILITY THAT IS CONTRADICTED BY THIS SECTION 14, THE TERMS WITH RESPECT TO LIMITATION OF LIABILITY SET FORTH IN SUCH SUBSEQUENT AGREEMENT WILL CONTROL AND SUPERSEDE THIS SECTION 14 WITH RESPECT TO SUCH PARTICULAR SERVICES.</p>
<p>FURTHER NOTWITHSTANDING THE FOREGOING, SOME OF THE FOREGOING EXCLUSIONS OF CERTAIN WARRANTIES AND/OR THE LIMITATION AND/OR EXCLUSION OF WARRANTIES MAY NOT APPLY TO YOU, SINCE SOME JURISDICTIONS DO NOT ALLOW IT.</p>
 
 
<h4>Indemnity</h4>
<p>You agree, as additional consideration for your use of the Services, to fully indemnify and hold harmless Traffic Roots and its officers, employees, agents, affiliates, partners, licensors, parents and subsidiaries from and against any demand or claim, including reasonable attorneys\\\' fees, made by any third party due to or arising out your use of the Services, your connection to the Services, your violations of the Terms, any Content you submit, post, transmit or otherwise make available through the Services, or your violation of any rights of another.</p>
 
<h4>General Provisions</h4>
<p>There shall be no third-party beneficiaries to your agreement with Traffic Roots pursuant to these Terms, except as may otherwise be expressly provided for herein</p>
<p>These Terms constitute the entire agreement between you and Traffic Roots and govern your use of the Services, superseding any prior agreements between you and Traffic Roots with respect to the Services. In certain circumstances, you may also be subject to additional terms and conditions applicable to purchases of certain products and or services available by or through&nbsp;<a href="http://www.trafficroots.com/">Traffic Roots</a>, whether made available directly by Traffic Roots or by certain of its affiliates and third-party providers.</p>
<p>These Terms, the Privacy Policy and such subsequent agreements as may be entered into by you in connection with the use of certain portions of the Services and your use of the Services in general shall be governed by the laws of the State of California without regard to any of its provisions regarding conflict of law. By using the Services, You agree to submit to the exclusive and personal jurisdiction of the courts located within the county of San Diego, California.</p>
<p>Any notices Traffic Roots may provide to you, including those with respect to a change of these Terms, may be made to you by postings on the Services or by e-mail. Any notices required by you hereunder shall be sent to Legal Department, Info (at) trafficroots.com, ATTN: Legal, via email.</p>
<p>If any clause or provision in these Terms, or the Privacy Policy or such subsequent agreements as may be entered into by you in connection with the use of certain portions of the Services and incorporated herein by reference is determined to be invalid or unenforceable by a court of competent jurisdiction or by operation of any applicable law, it will not affect the validity of any other clause or provision these Terms, or the Privacy Policy or such subsequent agreements as may be entered into by you in connection with the use of certain portions of the Services and incorporated herein by reference, which will remain in full force and effect; provided, however, that a court having jurisdiction may revise such provision to the extent necessary to make such provision valid and enforceable consistent with the intention of the parties.</p>
<p>The failure by Traffic Roots to exercise or enforce any of the terms or conditions of these Terms, or the Privacy Policy or such subsequent agreements as may be entered into by you in connection with the use of certain portions of the Services and incorporated herein by reference shall not constitute a waiver of Traffic Roots\\\' rights hereunder to enforce each and every term and condition of these Terms, or the Privacy Policy or such subsequent agreements as may be entered into by you in connection with the use of certain portions of the Services and incorporated herein by reference.</p>
<p>You may not assign any of your rights or responsibilities hereunder without first receiving the prior written consent of Traffic Roots.</p>
<p>The section headings contained in these Terms are solely for the purpose of reference and will not in any way affect the meaning or interpretation of these Terms.</p>
<p>You represent and warrant that by accepting these Terms and/or using the Services in any way, that you are not breaching any duty or obligation to any third-party and that the person executing this Agreement on behalf of it is the duly authorized representative of such party and authorized to bind it to the terms of this Agreement.</p>
<h4>Violations</h4>
<p>If you believe there have been any violations of these Terms, whether by you or another, you agree to report it to <a href="mailto:info@traffichaus.com">info (at)TrafficRoots.com</a> as soon as possible.</p>

					</div>
				</div>
			</div>
		</div>
	</div>
</div>
</div>
@endsection
